version: "3.8"

services:
  react-app:
    build: .
    container_name: react-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`avner.soudry-ort.online`)"
      - "traefik.http.routers.myapp.entrypoints=web"
      - "traefik.http.services.myapp.loadbalancer.server.port=3000"
    networks:
      - web_traefik

  mysql:
    image: mysql:8.0
    container_name: BDD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Mot de passe root
      MYSQL_DATABASE: football_db             # Nom de la base de données
      MYSQL_USER: user                    # Utilisateur
      MYSQL_PASSWORD: userpassword        # Mot de passe de l'utilisateur
    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql       # Pour persister les données
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Fichier SQL d'initialisatio
  
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    restart: always
    ports:
      - "80:80"      # HTTP
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/etc/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - web_traefik

volumes:
  mysql_data:

networks:
  web_traefik:
    driver: bridge