version: "3.8"

services:
  react-app:
    build: .
    container_name: react-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: BDD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Mot de passe root
      MYSQL_DATABASE: football_db             # Nom de la base de données
      MYSQL_USER: user                    # Utilisateur
      MYSQL_PASSWORD: userpassword        # Mot de passe de l'utilisateur
    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql       # Pour persister les données
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Fichier SQL d'initialisatio

volumes:
  mysql_data:
  
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./acme.json:/acme.json"
    environment:
      - CF_API_EMAIL=your-cloudflare-email@example.com
      - CF_API_KEY=your-cloudflare-api-key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"

  app:
    image: "myapp:latest"
    container_name: "myapp"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`avner.soudry-ort.online`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.myapp.loadbalancer.server.port=8000"
