name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Demande avant mise à jour des paquets
      - name: Confirm package update and OpenSSH installation
        run: echo "⚠️ Prêt à mettre à jour les paquets et installer OpenSSH ? (Oui/Non)"

      # 2️⃣ Mettre à jour les paquets et installer OpenSSH
      - name: Update packages and install OpenSSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Demande avant configuration de la clé SSH
      - name: Confirm SSH Key setup
        run: echo "⚠️ Prêt à configurer la clé SSH ? (Oui/Non)"

      # 3️⃣ Créer le répertoire .ssh et ajouter la clé privée
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Demande avant déploiement
      - name: Confirm AWS deployment
        run: echo "⚠️ Prêt à arrêter, supprimer et redéployer le conteneur ? (Oui/Non)"

      # 4️⃣ Se connecter au serveur AWS et effectuer le déploiement
      - name: Deploy application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}

            # Down le conteneur Docker
            echo "🛑 Arrêt du conteneur Docker..."
            docker compose down || docker stop mon_conteneur && docker rm mon_conteneur

            # Supprimer l'image Docker
            echo "🗑 Suppression de l'image Docker..."
            docker rmi mon_image || echo "Aucune image à supprimer"

            # Pull la dernière version du projet
            echo "🔄 Mise à jour du projet..."
            git pull origin main

            # Rebuild et redémarrage du conteneur
            echo "🚀 Reconstruction et démarrage du conteneur..."
            docker compose up --build -d

            # Afficher les logs pour vérification
            echo "📜 Logs du conteneur en cours..."
            docker logs -f mon_conteneur

            exit
          EOF

      # Demande avant suppression du répertoire .ssh
      - name: Confirm SSH Key cleanup
        run: echo "⚠️ Prêt à supprimer le répertoire .ssh pour la sécurité ? (Oui/Non)"

      # 5️⃣ Supprimer le répertoire .ssh pour la sécurité
      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh


