name: Deploy to AWS (Dev)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Vérifier et récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer le client SSH
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # 3️⃣ Configurer la clé SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 4️⃣ Tester la connexion SSH
      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ✅ Connexion SSH réussie !"

      # 5️⃣ Déployer l'application sur AWS
      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            set -e  # Stopper l'exécution en cas d'erreur

            echo "📂 Déplacement vers le répertoire de travail..."
            cd ${{ secrets.WORK_DIR }}

            # Vérifier qu'on est bien dans le bon répertoire
            pwd
            ls -la

            echo "🔄 Passage sur la branche main et pull du projet..."
            git checkout main
            git pull origin main

            # Vérifier la présence du fichier docker-compose.yml
            if [ ! -f "docker-compose.yml" ]; then
              echo "❌ Erreur : Fichier docker-compose.yml introuvable."
              exit 1
            fi

            echo "🛑 Arrêt et suppression des anciens conteneurs..."
            docker-compose down

            echo "🧹 Nettoyage des anciens conteneurs et images..."
            docker system prune -af

            echo "🚀 Reconstruction et démarrage des nouveaux conteneurs..."
            docker-compose up --build -d

            echo "✅ Déploiement terminé avec succès !"
          EOF

      # 6️⃣ Nettoyage des clés SSH pour la sécurité
      - name: Clean up SSH key
        run: rm -rf ~/.ssh



